package utiles.pdf;

public enum TituloPortada {

	 TITULO_LOGIN ("VERIFICACIÓN DEL LOGIN"),
	 TITULO_DESCARGAR_IGN ("VERIFICACIÓN DE LA DESCARGA GUÍA IGN"),
	 TITULO_DESCARGAR_IGCT ("VERIFICACIÓN DE LA DESCARGA GUÍA IGCT"),
	 TITULO_DESCARGAR_CONSULTADOCUMENTOS ("VERIFICACIÓN DE LA DESCARGA EN LA PANTALLA EN CONSULTA DE DOCUMENTOS"),
     TITULO_DESCARGAR_COORDINACION ("VERIFICACIÓN DE LA DESCARGA EN LA PANTALLA COORDINACIÓN"),
	 TITULO_DESCARGAR_INSTRUCCIONESGUIAS ("VERIFICACIÓN DE LA DESCARGA EN LA PANTALLA INSTURCCIONES GUÍAS"),
	 TITULO_DESCARGAR_FORMULARIOADIESTRAMIENTO("VERIFICACION DE LA DESCARGA DEL FORMULARIO DE ADIESTRAMIENTO");

private String titulo;
TituloPortada(String titulo) {
	// TODO Auto-generated constructor stub
	this.titulo=titulo;
}

public String getTitulo() {
	return titulo;
}

}
